AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template for a multi-tier VPC'
Metadata:
  License: Apache-2.0

Parameters:
  VpcCidr:
    Description: 'CIDR block for the VPC'
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetCidr:
    Description: 'CIDR block for the public subnet'
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnetCidr:
    Description: 'CIDR block for the private subnet'
    Type: String
    Default: 10.0.2.0/24

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MySampleVPC
          
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway
      
  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet
          
  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnetCidr
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # ... (Additional resources like Route Tables, NACLs, NAT Gateway, etc. would be added here)

Outputs:
  VPCId:
    Description: 'The ID of the newly created VPC'
    Value: !Ref MyVPC
  PublicSubnetId:
    Description: 'The ID of the public subnet'
    Value: !Ref MyPublicSubnet
